#include <stdio.h>
#include <stdlib.h>

#include "../include/functions.h"

/*
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
*/
int main(void)
{
    int total = even_fibonnacci_sum(4000000);
    printf("%d\n",total);
    return 0;
}