#!/usr/bin/env python3
##############################################################################
# Program by: James Lambert                                                  #
# Date Updated: 20220419                                                     #
##############################################################################
# Euler Problem 2 in Python                                                  #
# Even Fibonacci numbers                                                     #
# Each new term in the Fibonacci sequence is generated by adding the         #
# previous two terms. By starting with 1 and 2, the first 10 terms will be:  #
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                     #
# By considering the terms in the Fibonacci sequence whose values do not     #
# exceed four million, find the sum of the even-valued terms.                #
##############################################################################
import functions


def main():
    total = 0
    result = functions.list_fibonacci_numbers(4000000)
    for each in result:
        if each % 2 == 0:
            total += each
    print(total)


if __name__ == "__main__":
    main()
