#!/usr/bin/env python3
"""
Euler Problem 2: Even Fibonacci numbers

Code by: James Lambert
Date Updated: 20220419

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""
import functions


def main():
    """
    Determines all fibonacci numbers below 4,000,000 and provides
    the sum of all of the even ones
    """
    total = 0
    result = functions.list_fibonacci_numbers(4000000)
    for each in result:
        if each % 2 == 0:
            total += each
    print(total)


main()
